//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATPTopTen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ATPTopTen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;PlayerId&quot;:&quot;MC10&quot;,&quot;Rank&quot;:1,&quot;FirstName&quot;:&quot;Andy&quot;,&quot;LastName&quot;:&quot;Murray&quot;,&quot;NatlCode&quot;:&quot;GBR&quot;,&quot;Points&quot;:11960,&quot;IsTie&quot;:0},{&quot;PlayerId&quot;:&quot;D643&quot;,&quot;Rank&quot;:2,&quot;FirstName&quot;:&quot;Novak&quot;,&quot;LastName&quot;:&quot;Djokovic&quot;,&quot;NatlCode&quot;:&quot;SRB&quot;,&quot;Points&quot;:7915,&quot;IsTie&quot;:0},{&quot;PlayerId&quot;:&quot;W367&quot;,&quot;Rank&quot;:3,&quot;FirstName&quot;:&quot;Stan&quot;,&quot;LastName&quot;:&quot;Wawrinka&quot;,&quot;NatlCode&quot;:&quot;SUI&quot;,&quot;Points&quot;:5785,&quot;IsTie&quot;:0},{&quot;PlayerId&quot;:&quot;F324&quot;,&quot;Rank&quot;:4,&quot;FirstName&quot;:&quot;Roger&quot;,&quot;LastName&quot;:&quot;Federer&quot;,&quot;NatlCode&quot;:&quot;SUI&quot;,&quot;Points&quot;:5305,&quot;IsTie&quot;:0},{&quot;PlayerId&quot;:&quot;N409&quot;,&quot;Rank&quot;:5,&quot;FirstName&quot;:&quot;Rafael&quot;,&quot;LastName&quot;:&quot;Nadal&quot....
        /// </summary>
        internal static string PlayersJsonString {
            get {
                return ResourceManager.GetString("PlayersJsonString", resourceCulture);
            }
        }
    }
}
